### ISSUE TITLE
Error when trying to load API

### ISSUE THREAD

**Issue by hugo-pires** [tikalk/commandcar#8]
Hello

When I try to load an API with
commandcar load --location ...

I  get the following error
12 : Error: rsync exited with code 12

Could you help me ?
Thank you

**Comment by shaharsol** [comment]
It's either one of two:
1. maybe you should use sudo. when you load it actually syncs your files to a path under the global installation which can require sudo permissions
2. I'm thinking of a possible bug. If you never installed an existing command, and trying to load into a blank commandcar installation, then perhaps the it fails because it tries to sync into a non-existing directory.

Would appreciate if you let me know which it was, as (1) is already an issue it seems and (2) I need to fix if its really the problem

**Comment by casidiablo** [comment]
Same here. Using sudo yields another error:

```
sudo commandcar load --location ~/projects/ariel/commandcar/
Password:
error building db: Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/commandcar/node_modules/@commandcar'
loading /Users/cristian/projects/ariel/commandcar/
error building db: Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/commandcar/node_modules/@commandcar/commands/api.json'
```

In general I feel this project gives a step in the right direction, but there's many things that might benefit from more work:
- Documentation is poor:

> The best way to learn more about API definition would be to take a look at how we defined some basic APIs ourselves

No it is not. The best way to learn is to clearly explain in the `README` everything. For instance... the options array: what's `def`? definition? default?

Also the code in the examples is invalid JSON.
- Requiring `sudo` to load modules makes me cringe. Why is it necessary?
- Why are you guys using `rsync` for?
- Error messages are confusing or lacking. For instance:

```
commandcar non_extant.foo --post_id 123456789
```

Runs normally. It does not warn me that there's no `non_extant` API.
- Lack of modularization (or documentation?)... for instance, say all of the services require an `Authorization` header... do I have to define that in all of the 20 commands?

So, yeah... I feel all I can say for now is _nice try!_... and I will be definitely keep an eye on your project because I feel it could be useful.

**Comment by shaharsol** [comment]
@casidiablo thanks for the detailed response, I hear ya. I'm very happy with all the feedback commandcar got, I really didn't anticipate it, and yes I plan to improve it according to all this feedback.

As an immediate cure though for this said problem, the best thing is to run an install first like `sudo commandcar install --api instagram` which will create the node_mudules/@commandcar directory and hence enable further `load` commands.

**Comment by shaharsol** [comment]
This is no longer relevant in the new v0.1.1 which relies on swagger2.0. The entire model had changed, and sudo is also no longer necessary for anything other than initial npm installation. @casidiablo I know not everything is solved yet, but your feedback was epic, would appreciate if you have a look at the new v0.1.1 version and let me know how you feel about it.
